version: '3.9'

volumes:
  sa-postgres-data:

services:
  postgres:
    container_name: database-dev
    restart: unless-stopped
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - sa-postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
